# Generated by Django 3.2.9 on 2022-03-09 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercise_type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunningPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
            ],
            options={
                'verbose_name': '跑步计划',
                'verbose_name_plural': '跑步计划',
            },
        ),
        migrations.CreateModel(
            name='ExercisePlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exercise_type.strengthtrainingtype', verbose_name='项目名称')),
            ],
            options={
                'verbose_name': '力量训练计划',
                'verbose_name_plural': '力量训练计划',
            },
        ),
    ]
