# Generated by Django 3.2.9 on 2022-03-09 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_type', '0002_auto_20220310_0256'),
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseplanitem',
            name='type',
            field=models.ForeignKey(default='无', on_delete=django.db.models.deletion.CASCADE, to='exercise_type.strengthtrainingtype', to_field='name', unique=True, verbose_name='项目名称'),
            preserve_default=False,
        ),
    ]
