# Generated by Django 3.2.9 on 2022-03-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_alter_exerciseplanitem_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseplanitem',
            name='type',
            field=models.CharField(max_length=100, verbose_name='项目名称'),
        ),
    ]
