# Generated by Django 3.2.9 on 2022-03-09 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('running', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runningrecord',
            name='heart_rate_average',
            field=models.IntegerField(verbose_name='平均心率(跳/分钟)'),
        ),
        migrations.AlterField(
            model_name='runningrecord',
            name='heart_rate_max',
            field=models.IntegerField(verbose_name='最大心率(跳/分钟)'),
        ),
        migrations.AlterField(
            model_name='runningrecord',
            name='pace',
            field=models.FloatField(verbose_name='配速(分钟/千米)'),
        ),
        migrations.AlterField(
            model_name='runningrecord',
            name='speed',
            field=models.FloatField(verbose_name='速度(千米/小时)'),
        ),
        migrations.AlterField(
            model_name='runningrecord',
            name='step_frequency',
            field=models.IntegerField(verbose_name='步频(步/分钟)'),
        ),
        migrations.AlterField(
            model_name='runningrecord',
            name='step_length',
            field=models.FloatField(verbose_name='步长(米/步)'),
        ),
    ]
