# Generated by Django 3.2.9 on 2022-03-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('running', '0002_auto_20220309_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runningrecord',
            name='pace',
            field=models.FloatField(blank=True, verbose_name='配速(分钟/千米)'),
        ),
        migrations.AlterField(
            model_name='runningrecord',
            name='speed',
            field=models.FloatField(blank=True, verbose_name='速度(千米/小时)'),
        ),
    ]
