version: '1.0'
services:
  web:
    image: "zhoupp467/django-exercise-management"
    container_name: exercise-management-web
    entrypoint: ["/bin/sh", "/data/exercise_management/start.bat"]
    environment:
      - service_params=--settings.production
    volumes:
      - .:/data/exercise_management
      - /data/logs/exercise_management/
    ports:
      - "8000:8000"
      - "8001:8001"
    depends_on:
      - mysql
      - tengine
  mysql:
    image: "mysql"
    container_name: exercise-management-mysql
    restart: always
    environment:
      - "MYSQL_ROOT_PASSWORD=17701853425"
      - "MYSQL_DATABASE=exercise_management"
      - "TZ=Asia/Shanghai"
    ports:
      - "3306:3306"
  tengine:
    image: "zhoupp467/tengine"
    container_name: exercise-management-tengine
    ports:
      - "80:80"