# Generated by Django 3.2.9 on 2022-03-09 17:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StrengthTrainingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='项目名称')),
            ],
            options={
                'verbose_name': '项目列表',
                'verbose_name_plural': '项目列表',
            },
        ),
        migrations.CreateModel(
            name='StrengthTrainingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='日期')),
                ('weight', models.FloatField(verbose_name='重量(千克)')),
                ('repeat_times', models.IntegerField(verbose_name='重复次数')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exercise_type.strengthtrainingtype', verbose_name='项目名称')),
            ],
            options={
                'verbose_name': '健身记录',
                'verbose_name_plural': '健身记录',
            },
        ),
    ]
