# Generated by Django 3.2.9 on 2022-03-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_alter_exerciseplanitem_type'),
        ('exercise_type', '0002_auto_20220310_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strengthtrainingrecord',
            name='type',
            field=models.CharField(max_length=100, verbose_name='项目名称'),
        ),
        migrations.DeleteModel(
            name='StrengthTrainingType',
        ),
    ]
